# Generated by Django 4.1.5 on 2023-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_vehicle_days_parked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="completion_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="creation_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="service_request_number",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_color",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_make",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True
            ),
        ),
    ]
