# Generated by Django 4.1.6 on 2023-02-12 22:11

from django.db import migrations

DDL_MIGRATE_VEHICLE = [
    """
    ALTER TABLE main_criminalvehicle RENAME TO main_criminalvehicle_old;
    ALTER TABLE public.main_criminalvehicle_old
        DROP CONSTRAINT main_criminalvehicle_pkey;

    CREATE TABLE public.main_criminalvehicle (
        vehicle_ptr_id bigint NOT NULL,
        top_secret boolean NOT NULL,
        police_data jsonb NOT NULL
    ) PARTITION BY RANGE(vehicle_ptr_id);

    ALTER TABLE public.main_criminalvehicle OWNER TO geo;
    ALTER TABLE public.main_criminalvehicle
        ADD CONSTRAINT main_criminalvehicle_pkey PRIMARY KEY (vehicle_ptr_id);
    """,
    """
    CREATE TABLE main_criminalvehicle_1_100000 PARTITION OF main_criminalvehicle
        FOR VALUES FROM (1) TO (100000);

    CREATE TABLE main_criminalvehicle_100000_200000 PARTITION OF main_criminalvehicle
        FOR VALUES FROM (100000) TO (200000);

    CREATE TABLE main_criminalvehicle_200000_300000 PARTITION OF main_criminalvehicle
        FOR VALUES FROM (200000) TO (300000);

    CREATE TABLE main_criminalvehicle_300000_400000 PARTITION OF main_criminalvehicle
        FOR VALUES FROM (300000) TO (400000);
    """,
    """
    INSERT INTO main_criminalvehicle SELECT * FROM main_criminalvehicle_old;
    DROP TABLE main_criminalvehicle_old;
    """,
    """
    ALTER TABLE main_criminalvehicle
        DROP CONSTRAINT IF EXISTS main_criminalvehicle_vehicle_ptr_id_e2c1bd98_fk_main_vehicle_id;
    ALTER TABLE main_mistakevehicle
        DROP CONSTRAINT IF EXISTS main_mistakevehicle_vehicle_ptr_id_39a2a96c_fk_main_vehicle_id;
    ALTER TABLE main_reporter_reports
        DROP CONSTRAINT IF EXISTS main_reporter_reports_vehicle_id_79517bd8_fk_main_vehicle_id;
    ALTER TABLE main_repeatedvehicle
        DROP CONSTRAINT IF EXISTS main_repeatedvehicle_vehicle_ptr_id_34a76dba_fk_main_vehicle_id;
    ALTER TABLE main_repeatedvehicle
        DROP CONSTRAINT IF EXISTS main_repeatedvehicle_previous_event_id_cf91afee_fk_main_vehi;
    ALTER TABLE main_comment
        DROP CONSTRAINT main_comment_vehicle_id_4709556a_fk_main_vehicle_id;
    """,
    """
    ALTER TABLE public.main_vehicle
        DROP CONSTRAINT main_vehicle_pkey;

    ALTER TABLE main_vehicle RENAME TO main_vehicle_old;
    ALTER SEQUENCE public.main_vehicle_id_seq RENAME TO main_vehicle_id_seq_old;

    CREATE TABLE public.main_vehicle (
        id bigint NOT NULL,
        creation_date date NOT NULL,
        status character varying(20),
        completion_date date,
        service_request_number character varying(50) NOT NULL,
        type_of_service_request character varying(255) NOT NULL,
        license_plate character varying(1000),
        vehicle_make character varying(250),
        vehicle_color character varying(250),
        current_activity character varying(250),
        most_recent_action character varying(250),
        days_parked bigint,
        street_address character varying(250),
        zip_code character varying(10),
        x_coordinate double precision,
        y_coordinate double precision,
        ward integer,
        police_district integer,
        community_area integer,
        ssa integer,
        latitude double precision,
        longitude double precision,
        location public.geometry(Point,4326),
        responsible_id bigint
    ) PARTITION BY RANGE(id);

    """,
    """
    ALTER TABLE public.main_vehicle OWNER TO geo;
    ALTER TABLE public.main_vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.main_vehicle_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE main_vehicle_1_100000 PARTITION OF main_vehicle
        FOR VALUES FROM (1) TO (100000);

    CREATE TABLE main_vehicle_100000_200000 PARTITION OF main_vehicle
        FOR VALUES FROM (100000) TO (200000);

    CREATE TABLE main_vehicle_200000_300000 PARTITION OF main_vehicle
        FOR VALUES FROM (200000) TO (300000);

    CREATE TABLE main_vehicle_300000_400000 PARTITION OF main_vehicle
        FOR VALUES FROM (300000) TO (400000);

    INSERT INTO main_vehicle SELECT * FROM main_vehicle_old;
    SELECT setval('main_vehicle_id_seq', nextval('main_vehicle_id_seq_old'::regclass), false);
    DROP TABLE main_vehicle_old;
    """,
    """
    ALTER TABLE public.main_vehicle
        ADD CONSTRAINT main_vehicle_pkey PRIMARY KEY (id);

    CREATE INDEX main_vehicle_completion_date_e62c3b9d ON public.main_vehicle USING btree (completion_date);
    CREATE INDEX main_vehicle_creation_date_41b48ffb ON public.main_vehicle USING btree (creation_date);
    CREATE INDEX main_vehicle_location_55ff4376_id ON public.main_vehicle USING gist (location);
    CREATE INDEX main_vehicle_responsible_id_cbe5a195 ON public.main_vehicle USING btree (responsible_id);
    CREATE INDEX main_vehicle_service_request_number_746fff87 ON public.main_vehicle USING btree (service_request_number);
    CREATE INDEX main_vehicle_service_request_number_746fff87_like ON public.main_vehicle USING btree (service_request_number varchar_pattern_ops);
    CREATE INDEX main_vehicle_vehicle_color_9bf200f6 ON public.main_vehicle USING btree (vehicle_color);
    CREATE INDEX main_vehicle_vehicle_color_9bf200f6_like ON public.main_vehicle USING btree (vehicle_color varchar_pattern_ops);
    CREATE INDEX main_vehicle_vehicle_make_28790aba ON public.main_vehicle USING btree (vehicle_make);
    CREATE INDEX main_vehicle_vehicle_make_28790aba_like ON public.main_vehicle USING btree (vehicle_make varchar_pattern_ops);

    ALTER TABLE public.main_vehicle
        ADD CONSTRAINT main_vehicle_responsible_id_cbe5a195_fk_main_responsible_id FOREIGN KEY (responsible_id) REFERENCES public.main_responsible(id) DEFERRABLE INITIALLY DEFERRED;
    """,
    """
    ALTER TABLE main_criminalvehicle
        ADD CONSTRAINT main_criminalvehicle_vehicle_ptr_id_e2c1bd98_fk_main_vehicle_id
        FOREIGN KEY (vehicle_ptr_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_mistakevehicle
        ADD CONSTRAINT main_mistakevehicle_vehicle_ptr_id_39a2a96c_fk_main_vehicle_id
        FOREIGN KEY (vehicle_ptr_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_reporter_reports
        ADD CONSTRAINT main_reporter_reports_vehicle_id_79517bd8_fk_main_vehicle_id
        FOREIGN KEY (vehicle_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_repeatedvehicle
        ADD CONSTRAINT main_repeatedvehicle_vehicle_ptr_id_34a76dba_fk_main_vehicle_id
        FOREIGN KEY (vehicle_ptr_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_repeatedvehicle
        ADD CONSTRAINT main_repeatedvehicle_previous_event_id_cf91afee_fk_main_vehi
        FOREIGN KEY (previous_event_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_comment
        ADD CONSTRAINT main_comment_vehicle_id_4709556a_fk_main_vehicle_id
        FOREIGN KEY (vehicle_id) REFERENCES main_vehicle(id);
    """,
    """
    ALTER TABLE main_comment RENAME TO main_comment_old;
    ALTER TABLE public.main_comment_old
        DROP CONSTRAINT main_comment_pkey;
    ALTER SEQUENCE public.main_comment_id_seq RENAME TO main_comment_id_seq_old;

    CREATE TABLE public.main_comment (
        id bigint NOT NULL,
        name character varying(255) NOT NULL,
        text text NOT NULL,
        vehicle_id bigint NOT NULL
    ) PARTITION BY RANGE(vehicle_id);

    ALTER TABLE public.main_comment OWNER TO geo;

    CREATE TABLE main_comment_1_100000 PARTITION OF main_comment
        FOR VALUES FROM (1) TO (100000);

    CREATE TABLE main_comment_100000_200000 PARTITION OF main_comment
        FOR VALUES FROM (100000) TO (200000);

    CREATE TABLE main_comment_200000_300000 PARTITION OF main_comment
        FOR VALUES FROM (200000) TO (300000);

    CREATE TABLE main_comment_300000_400000 PARTITION OF main_comment
        FOR VALUES FROM (300000) TO (400000);

    ALTER TABLE public.main_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.main_comment_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    ALTER TABLE public.main_comment
        ADD CONSTRAINT main_comment_pkey PRIMARY KEY (vehicle_id, id);
    INSERT INTO main_comment SELECT * FROM main_comment_old;

    SELECT setval('main_comment_id_seq', nextval('main_comment_id_seq_old'::regclass), false);

    DROP TABLE main_comment_old;

    CREATE INDEX main_comment_vehicle_id_4709556a ON public.main_comment USING btree (vehicle_id);
    ALTER TABLE public.main_comment
        ADD CONSTRAINT main_comment_vehicle_id_4709556a_fk_main_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES public.main_vehicle(id) DEFERRABLE INITIALLY DEFERRED;
    """,
]


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_criminalvehicle_mistakevehicle_responsible_reporter_and_more"),
    ]

    operations = [migrations.RunSQL(i) for i in DDL_MIGRATE_VEHICLE]
